Futher improvements in components implementation
LordOfPolls/discord-py-slash-command pull request #204
Opened 2021-06-07 19:47 UTC by artem30801

## About this pull request

Futher improvements in components implementation
Cherry-picked commits from previous draft to improve commit log

## Changes

- Support for both message and components as kwargs in wait_for_component
- Support for actionrows and lists of actionrows in wait_for_component
- Exception for hidden+edit_origin in defer
- Warning for edit_origin=True defer when sending response
- Warning for edit_origin=False defer when calling edit_origin
- Move component enums to models

What changes were made?

## Checklist

- [X] I've checked this pull request runs on `Python 3.6.X`.
- [ ] This fixes something in [Issues](https://github.com/eunwoo1104/discord-py-slash-command/issues).
    - Issue:
- [X] This adds something new.
- [X] There is/are breaking change(s).
- [X] (If required) Relevant documentation has been updated/added.
- [ ] This is not a code change. (README, docs, etc.)

2021-06-08 08:07 UTC, LordOfPolls approved these changes

2021-06-08 17:10 UTC, goverfl0w commented on discord_slash/dpy_overrides.py
> +        return None
Is this a required return type needed?

2021-06-08 17:11 UTC, goverfl0w commented on discord_slash/dpy_overrides.py
> +                if component["custom_id"] == custom_id:
`is` operator would be a faster method to approaching checking the component's custom ID, especially if we have numerous ones and many action rows, likely a better approach IMO for large-scaled commands in bots.

2021-06-08 17:16 UTC, goverfl0w commented on discord_slash/utils/manage_components.py
> +            f"Unknown component type of {message} ({type(message)}). "
I feel sure when you `raise` an error exception in Python you're required to give a comma or concatenate the strings.

2021-06-08 17:16 UTC, goverfl0w requested changes
Some minor changes requested.

2021-06-11 20:45 UTC, artem30801 commented
Thank you very much for your feedback, I applied requested changes

2021-06-11 20:47 UTC, goverfl0w approved these changes

2021-06-11 21:41 UTC, LordOfPolls approved these changes

2021-06-11 21:42 UTC, merged